// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        //jcenter() // Add this line if not already present
        maven { url "https://jitpack.io" }
        maven { url 'https://repo1.maven.org/maven2' }
        maven { url 'https://maven.google.com' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.github.dcendents:android-maven-plugin:1.2' // Updated to latest version
        classpath 'com.jakewharton:butterknife-gradle-plugin:10.2.3' // Updated to latest version
        classpath 'com.google.gms:google-services:4.3.10' // Updated to latest version
    }
}

allprojects {
    repositories {
        google()

        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url 'https://dl.bintray.com/sj/maven/' }
        maven { url 'https://maven.google.com' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    rxJavaVer = '1.1.6'
    rxAndroidVer = '1.2.1'
    butterknifeVer = '10.2.3' // Updated to latest version
}
