apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    compileSdkVersion 30
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        sourceSets {
            main {
                java.srcDirs = ['src']
                res.srcDirs = ['res']
                assets.srcDirs = ['assets']
                manifest.srcFile 'AndroidManifest.xml'
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    google()
    mavenCentral()
    maven { url "https://jitpack.io" }

    //  jcenter()  // Add this if necessary
    maven {
        url 'https://oss.jfrog.org/artifactory/oss-snapshot-local'
        allowInsecureProtocol true
    }
}

//dependencies {
//    compileOnly 'io.realm:realm-android:0.87.5'
//    annotationProcessor 'io.realm:realm-android:0.87.5'
//    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
//}

dependencies {
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
    implementation 'io.realm:realm-android-library:10.11.1'
}

task sourceJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}

task javadoc(type: Javadoc) {
    failOnError false
    source = android.sourceSets.main.java.sourceFiles
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            afterEvaluate {
                from components.release
            }
            groupId = 'com.yourcompany'
            artifactId = 'mpchartlib'
            version = '1.0.0'

            artifact sourceJar
            artifact javadocJar
        }
    }
}
artifacts {
    archives sourceJar
    archives javadocJar
}
